HexaEdge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from saler.views import admin2

urlpatterns = [
    path('wrappers/india/my/admin/pannel/home/', admin.site.urls),
    path('wrappers/india/my/admin/pannel/admin20/', admin2, name = 'admin2'),
    path('', include('main.urls')),
    path('seller/', include('saler.urls')),
    path("login/", auth_views.LoginView.as_view(template_name='main/login.html', redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'), name="password_reset_complete"),
    path("coupon/",include('coupon.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name="signup"),
    path('account_settings/', views.account_settings, name="account_settings"),
    path("product/<int:prod_id>", views.productView, name="ProductView"),
    path('contact/', views.contact, name="contact"),
    path("products/<str:catg>", views.view_all, name="products_view_all"),
    path('plus_element_cart/', views.plus_element_cart),
    path('minus_element_cart/', views.minus_element_cart),
    path('add_to_cart/', views.add_to_cart),
    path('delete_from_cart/', views.delete_from_cart),
    path('dummy_cart/', views.dummy_cart),
    path('cart/', views.cart, name="main_cart"),
    path('checkout/', views.checkout, name="main_checkout"),
    path('razor/', views.razor, name="razor"),
    path('xyz/', views.xyz, name="xyz"),
    path('payment_status/', views.payment_status, name="payment_status"),
    path('order_now/', views.order_now, name="order_now"),
    path('myorders/', views.MyOrders, name="myorders"),
    path('search/', views.search, name="search"),
    path('MenuFilter/<str:querys>', views.MenuFilter, name="MenuFilter"),
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    ]

saler/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.dashboard, name = 'dashboard'),
		path('home/', views.index, name = 'saler_home'),
        path('seller_signup/', views.seller_signup, name="seller_signup"),
    	path('account_settings/', views.account_settings, name="saler_account_settings"),
    	path('add_product/', views.add_product, name="add_product"),
    	path('view_products/', views.view_products, name="view_products"),
    	path('plus_element_cart/', views.plus_element_cart),
    	path('minus_element_cart/', views.minus_element_cart),
    	path('add_to_cart/', views.add_to_cart),
    	path('delete_from_cart/', views.delete_from_cart),
        path('cart/', views.mycart, name="cart"),
    	path('MyOrders/', views.MyOrders, name="seller_orders"),
    	path("products/<str:catg>", views.view_all, name="saler_products_view_all"),
    	path("product/<int:prod_id>", views.productView, name="SalerProductView"),
    	path("checkout/", views.checkout, name = "checkout")

	]

saler/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class SalerDetail(models.Model):
	SEX_CHOICES = (("Male",'Male'),("Female",'Female'),("Other",'Other'))
	STATE_CHOICES = (
		("Andaman & Nicobar Islands",'Andaman & Nicobar Islands'),
		("Andhra Pradesh",'Andhra Pradesh'),
		("Arunachal Pradesh",'Arunachal Pradesh'),
		("Assam",'Assam'),
		("Bihar",'Bihar'),
		("Chandigarh",'Chandigarh'),
		("Chhattisgarh",'Chhattisgarh'),
		("Dadra & Nagar Haveli",'Dadra & Nagar Haveli'),
		("Daman and Diu",'Daman and Diu'),
		("Delhi",'Delhi'),
		("Goa",'Goa'),
		("Gujarat",'Gujarat'),
		("Haryana",'Haryana'),
		("Himachal Pradesh",'Himachal Pradesh'),
		("Jammu & Kashmir",'Jammu & Kashmir'),
		("Jharkhand",'Jharkhand'),
		("Karnataka",'Karnataka'),
		("Kerala",'Kerala'),
		("Lakshadweep",'Lakshadweep'),
		("Madhya Pradesh",'Madhya Pradesh'),
		("Maharashtra",'Maharashtra'),
		("Manipur",'Manipur'),
		("Meghalaya",'Meghalaya'),
		("Mizoram",'Mizoram'),
		("Nagaland",'Nagaland'),
		("Odisha",'Odisha'),
		("Puducherry",'Puducherry'),
		("Punjab",'Punjab'),
		("Rajasthan",'Rajasthan'),
		("Sikkim",'Sikkim'),
		("Tamil Nadu",'Tamil Nadu'),
		("Telangana",'Telangana'),
		("Tripura",'Tripura'),
		("Uttarakhand",'Uttarakhand'),
		("Uttar Pradesh",'Uttar Pradesh'),
		("West Bengal",'West Bengal'),
		)
	user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
	photo = models.ImageField(default='default.png',upload_to='user_photos')
	mobile = models.CharField(max_length=10,null=True)
	gst_Number = models.CharField(max_length=15,null=True)
	shop_Name = models.CharField(max_length=500,null=True)
	alternate_mobile = models.CharField(max_length=10,null=True,blank=True)
	shop_Address = models.TextField()
	pincode = models.CharField(max_length=6, null=True)
	landmark = models.CharField(max_length=500, null=True, blank=True)
	locality = models.CharField(max_length=100, null=True, blank=True)
	city = models.CharField(max_length=100, null=True, blank=True)
	state = models.CharField(max_length=50,choices=STATE_CHOICES, null=True)
	account_Holder_Name = models.CharField(max_length=50, null=True)
	account_Number = models.CharField(max_length=20, null=True)
	ifsc_Code = models.CharField(max_length=11, null=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.photo.path)
		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.photo.path)

class SellerSlider(models.Model):
	name = models.CharField(max_length=50, default = "", null=True)
	image = models.ImageField(upload_to='seller_slider_img')
	url = models.CharField(max_length=200, default = "#", null=True)

	def __str__(self):
		return f'{self.name}'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image.path)
		if img.height > 1024 or img.width > 1024:
			output_size = (1024, 1024)
			img.thumbnail(output_size)
			img.save(self.image.path)


class category(models.Model):
	name = models.CharField(max_length=50, default="")
	sub_Categories  = models.TextField(default="")
	def __str__(self):
		return f'{self.name}'

class Product(models.Model):
	GST_CHOICES = (("0",'0'),("3",'3'),("5",'5'),("12",'12'),("18",'18'),("28",'28'))
	product_id = models.BigAutoField(primary_key=True)
	product_id2 = models.CharField(max_length=100,default='')
	shop = models.ForeignKey(User, on_delete=models.CASCADE,default='')
	product_name = models.CharField(max_length=100)
	category = models.ForeignKey(category, default="", verbose_name="Category", on_delete=models.SET_DEFAULT, null=True)
	subcategory = models.CharField(max_length=50, default="")
	price = models.IntegerField(default=0)
	price_not = models.IntegerField(default=999)
	desc = models.TextField()
	gst = models.CharField(default='0',max_length=3,choices=GST_CHOICES)
	pub_date = models.DateField(auto_now=True)
	image1 = models.ImageField(upload_to='products/images', default="",null=True)
	image2 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image3 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image4 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image5 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img1 = Image.open(self.image1.path)
		if img1.height > 1500 or img1.width > 1500:
			output_size = (1500, 1500)
			img1.thumbnail(output_size)
			img1.save(self.image1.path)
		if self.image2:
			img2 = Image.open(self.image2.path)
			if img2.height > 1500 or img2.width > 1500:
				output_size = (1500, 1500)
				img2.thumbnail(output_size)
				img2.save(self.image2.path)

		if self.image3:
			img3 = Image.open(self.image3.path)
			if img3.height > 1500 or img3.width > 1500:
				output_size = (1500, 1500)
				img3.thumbnail(output_size)
				img3.save(self.image3.path)

		if self.image4:
			img4 = Image.open(self.image4.path)
			if img4.height > 1500 or img4.width > 1500:
				output_size = (1500, 1500)
				img4.thumbnail(output_size)
				img4.save(self.image4.path)

		if self.image5:
			img5 = Image.open(self.image5.path)
			if img5.height > 1500 or img5.width > 1500:
				output_size = (1500, 1500)
				img5.thumbnail(output_size)
				img5.save(self.image5.path)
	def __str__(self):
		return f'{self.product_id}'

class ProductSize(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	size = models.CharField(max_length=20)
	quantity = models.IntegerField(default=0, null=True)

class ProductReview(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	review = models.TextField()
	time = models.DateTimeField(auto_now=True)

class WholeSaleProduct(models.Model):
	SEX_CHOICES = (("Male",'Male'),("Female",'Female'),("All",'All'))
	product_id = models.BigAutoField(primary_key=True)
	product_name = models.CharField(max_length=100)
	category = models.ForeignKey(category, default="", verbose_name="Category", on_delete=models.SET_DEFAULT)
	subcategory = models.CharField(max_length=50, default="")
	price = models.IntegerField(default=0)
	desc = models.TextField()
	size = models.TextField(verbose_name='Size Avialabe(Separated by Comma)')
	color = models.TextField(verbose_name='Enter Color Separated by Comma')
	min_Quantity = models.IntegerField(default=0, null=True)
	pub_date = models.DateField(auto_now=True)
	image1 = models.ImageField(upload_to='products/images', default="",null=True)
	image2 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image3 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image4 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image5 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img1 = Image.open(self.image1.path)
		if img1.height > 1500 or img1.width > 1500:
			output_size = (1500, 1500)
			img1.thumbnail(output_size)
			img1.save(self.image1.path)
		if self.image2:
			img2 = Image.open(self.image2.path)
			if img2.height > 1500 or img2.width > 1500:
				output_size = (1500, 1500)
				img2.thumbnail(output_size)
				img2.save(self.image2.path)

		if self.image3:
			img3 = Image.open(self.image3.path)
			if img3.height > 1500 or img3.width > 1500:
				output_size = (1500, 1500)
				img3.thumbnail(output_size)
				img3.save(self.image3.path)

		if self.image4:
			img4 = Image.open(self.image4.path)
			if img4.height > 1500 or img4.width > 1500:
				output_size = (1500, 1500)
				img4.thumbnail(output_size)
				img4.save(self.image4.path)

		if self.image5:
			img5 = Image.open(self.image5.path)
			if img5.height > 1500 or img5.width > 1500:
				output_size = (1500, 1500)
				img5.thumbnail(output_size)
				img5.save(self.image5.path)
	def __str__(self):
		return f'{self.product_id}'

class WholeSaleProductOrders(models.Model):
	STATUS_CHOICES = (("Accepted",'Accepted'),("Packed",'Packed'),("On The Way",'On The Way'),("Delivered",'Delivered'),("Cancel",'Cancel'))
	order_id = models.CharField(max_length=50,default='')
	user = models.ForeignKey(User, default='', on_delete=models.CASCADE)
	products = models.CharField(max_length=50)
	status = models.CharField(max_length=15,choices=STATUS_CHOICES,default='')

class dow(models.Model):
	product = models.OneToOneField(Product, default="", verbose_name="Product Id", on_delete=models.CASCADE, null=True)
	price = models.PositiveIntegerField()
	def __str__(self):
		return f'{self.product}'

class trend(models.Model):
	product = models.OneToOneField(Product, default="", on_delete=models.CASCADE, null=True)
	number = models.PositiveIntegerField()
	def __str__(self):
		return f'{self.product}'

class MyCart(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product_id = models.CharField(max_length=100)
	number = models.PositiveIntegerField(default=0)

class Orders(models.Model):
	STATUS_CHOICES = (("Accepted",'Accepted'),("Packed",'Packed'),("On The Way",'On The Way'),("Delivered",'Delivered'),("Cancel",'Cancel'))
	order_id = models.CharField(max_length=50,default='')
	saler = models.CharField(max_length=100,default='wrappers@admin',)
	user = models.ForeignKey(User, default='', on_delete=models.CASCADE)
	products = models.CharField(max_length=50)
	size = models.CharField(max_length=50,default='',null=True)
	status = models.CharField(max_length=15,choices=STATUS_CHOICES,default='')

saler/forms.py
from .models import SalerDetail, Product
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class SalerRegisterForm(UserCreationForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={}))
	username = forms.CharField(label=("Mobile Number/Email"),widget=forms.TextInput(attrs={'oninput':'validate()'}))
	gst = forms.CharField(label=("GST Number"),widget=forms.TextInput(attrs={}))
	shop = forms.CharField(label=("Company/Shop Name"),widget=forms.TextInput(attrs={}))
	password1 = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={}),)
	password2  = forms.CharField(label=("Confirm"), strip=False, widget=forms.PasswordInput(attrs={}),)
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'password1', 'password2','gst', 'shop']

class SalerAddressForm(forms.ModelForm):
	shop_Address = forms.CharField(widget=forms.TextInput(attrs={}))
	locality = forms.CharField(required =True)
	city = forms.CharField(required =True)
	alternate_mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Alternate Mobile No(optional)'}), required = False)
	landmark = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Landmark(optional)'}), required = False)
	class Meta:
		model = SalerDetail
		fields = [
			'mobile',
			'shop_Name',
			'alternate_mobile',
			'shop_Address',
			'pincode',
			'landmark',
			'locality',
			'city',
			'state',
		]
class UpdateSalerDetailForm(forms.ModelForm):
	class Meta:
		model = SalerDetail
		fields = [
			'photo',
			'mobile',
			'shop_Name',
			'gst_Number',
			'alternate_mobile',
			'shop_Address',
			'pincode',
			'landmark',
			'locality',
			'city',
			'state',
		]

class UpdateSalerAccountDetailForm(forms.ModelForm):
	class Meta:
		model = SalerDetail
		fields = [
			'account_Holder_Name',
			'account_Number',
			'ifsc_Code',
			]

saler/templates/saler/account_settings.html
{% extends "saler/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block saler_head %}
	<style type="text/css">
		.detail_heading{
				color: #080d2b;
				font-family: Candara;
		}

		.btn{
			
		}

		.btn a{
			color: #080d2b;
			text-decoration: none;
		}

		.btn:active{
			border: solid 1px #ff4500;
			border-radius: 0;
		}


		.detail{
			-webkit-box-shadow: 0 0 10px rgba(0,0,0,0.17);
		    -moz-box-shadow: 0 0 10px rgba(0,0,0,0.17);
		    -ms-box-shadow: 0 0 10px rgba(0,0,0,0.17);
		    -o-box-shadow: 0 0 10px rgba(0,0,0,0.17);
		    box-shadow: 0 0 10px rgba(0,0,0,0.17); 
		}
		@media(min-width:420px){
			.detail_heading{
				font-size: 55px;
				letter-spacing: 3px;
				
			}
		}

		.removeing br{
			display: none;
		}
		.removeing a{
			display: none;
		}
		.form-group textarea{
			height: 63px;
		}

		.sub_btn{
			height: 30px;
			width: 150px;
			color: #fff;
			font-weight: bold;
			border: 0;
			border-radius: 3px;
			background-color: #080d2b;
		}
		.sub_btn:hover{
			background-color: #ff4500;
			color: #f4f4f4;
		}
		@media(max-width: 420px){
			
		}

	</style>

	<script>
		function change(b_id)
		{	

			if (b_id == "change_pass") {
				document.getElementById("account_update").style.display = 'none';
				document.getElementById(b_id).style.display="block";
				document.getElementById("disp_setting").style.display = 'none';
			}
			else if (b_id == "disp_setting") {
				document.getElementById("account_update").style.display = 'none';
				document.getElementById("change_pass").style.display="none";
				document.getElementById(b_id).style.display = 'block';
			}

			else{
				document.getElementById("account_update").style.display = 'block';
				document.getElementById("change_pass").style.display="none";
				document.getElementById("disp_setting").style.display = 'none';
			}
		}
	</script>
{% endblock saler_head %}

{% block saler_body %}
	{% if messages %}
     {% for message in messages %}
             <div class="alert alert-{{message.tags}} alert-dismissible fade show">{{ message }}</div>
     {% endfor %}
    {% endif %}
    <div class="container pt-1">
    	<div class="row">
			<div class="col-md-3" >
				<img src="{% static 'main/images/logo2.png' %}" style="width: 100%; height: 80px;">
			</div>
			<div class="col-md-9" align="center">
				<h3 class="detail_heading mt-1">Seller Account Settings</h3>
			</div>

		</div>
		<hr class="mb-1 mt-1">
    	<div class="row">
			<div class="col-md-3 mt-2">
				<div class="card">
					<button type="button" class="btn"  onclick="change('account_update')"><a href="#detail">Update Profile</a></button><hr class="mt-0 mb-0">
					<button type="button" class="btn" onclick="change('change_pass')"><a href="#detail">Change Password</a></button><hr class="mt-0 mb-0">
					<button type="button" class="btn" onclick="change('disp_setting')"><a href="#detail">Bank Details</a></button><hr class="mt-0 mb-0">
					
				</div>
			</div>
			<div class="col-md-9 mt-2">
				<!-- Update Details -->
				<div class="card detail" id="account_update" style="display: block;">
					<h4 class="ml-3 mt-2"  style="color: #080d2b; font-family: Comic Sans MS;">Your Details</h4>
					<hr class="mt-1 mb-0">
					<form method="POST" class="signup_form mr-3 ml-3 mt-1" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-row">
					      <div class="form-group col-md-3 mb-0">
					        {{ u_form.first_name | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-3 mb-0">
					        {{ u_form.last_name | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-2 mb-0">
					        {{ s_form.shop_Name | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-2 mb-0">
					        {{ s_form.mobile | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-2 mb-0">
					        {{ s_form.alternate_mobile | as_crispy_field }}
					      </div>
					    </div>
						
						<div class="form-row">
					      <div class="form-group col-md-4 mb-0">
					        {{ u_form.email | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-3 mb-0">
					        {{ s_form.gst_Number | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-2 mb-0">
					        {{ s_form.landmark | as_crispy_field }}
					      </div>
					       <div class="form-group col-md-3 mb-0">
					        {{ s_form.locality | as_crispy_field }}
					      </div>
					      
					    </div>
						<div class="form-row">
					      
					      <div class="form-group col-md-8 mb-0">
					        {{ s_form.shop_Address | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-4 mb-0 removeing">
					        {{ s_form.photo | as_crispy_field }}
					      </div>					      
					    </div>
					    <div class="form-row">
					      
					      <div class="form-group col-md-4 mb-0">
					        {{ s_form.city | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-4 mb-0 removeing">
					        {{ s_form.state | as_crispy_field }}
					      </div>
					      <div class="form-group col-md-4 mb-0 removeing">
					        {{ s_form.pincode | as_crispy_field }}
					      </div>					      
					    </div>
						<section class="mr-1 mb-5">
							<button type="submit" class="sub_btn" style="float: right;">Update</button>
						</section>
					</form>
				</div>

				<!-- Change Password -->
				<div class="card detail" id="change_pass" style="display: none;">
					<h4 class="ml-3 mt-2"  style="color: #080d2b; font-family: Comic Sans MS;">Change Password</h4>
					<hr class="mt-1 mb-0">
					<form method="POST" class="signup_form mr-3 ml-3 mt-1" enctype="multipart/form-data">
						{% csrf_token %}
						<fieldset>
							{{ pass_change_form | crispy}}
						</fieldset>
						<section class="mt-4 mr-1 ml-1">
							<button type="submit" class="sub_btn" style="float: right; margin-top: -45px; width: 200px;">Change Password</button>
						</section>
					</form>
				</div>

				<!-- Account Settings -->
				<div class="card detail pb-3" id="disp_setting" style="display: none;">
					<h4 class="ml-3 mt-2"  style="color: #080d2b; font-family: Comic Sans MS;">Bank Account</h4>
					<hr class="mt-1 mb-0">
					<form method="POST" class="signup_form mr-3 ml-3 mt-1" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-row">
					      <div class="form-group col-md mb-0">
					        {{ acc_form.account_Holder_Name | as_crispy_field }}
					      </div>
					      <div class="form-group col-md mb-0">
					        {{ acc_form.ifsc_Code | as_crispy_field }}
					      </div>
					    </div>
						<div class="form-row">
					      <div class="form-group col-md mb-0">
					        {{ acc_form.account_Number | as_crispy_field }}
					      </div>
					      
					    </div>
					    <section class="mt-4 mr-1 ml-1">
							<button type="submit" class="sub_btn" style="float: right; margin-top: -25px; width: 200px;">Save</button>
						</section>
					</form>
				</div>
			</div>
    </div>

    <script type="text/javascript">
    	 function hexCode(i) { 
                return ("0" + parseInt(i).toString(16)).slice(-2); 
            }
    		rgb = document.body.style.backgroundColor;
            rgb = rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/); 
            hex = "#" + hexCode(rgb[1]) + hexCode(rgb[2])  + hexCode(rgb[3]); 
    	document.getElementById('select_bgcolor').value = hex;
    </script>
    <script>
      $(document).on('change',"#id_gst_Number", function(){
        var inputvalues = $(this).val();
        var gstinformat = new RegExp('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$');

        if (gstinformat.test(inputvalues)) {
         return true;
        } else {
            alert('Please Enter Valid GSTIN Number');
            $("#id_gst_Number").val('');
            $("#id_gst_Number").focus();
        }

    });

      $("#id_ifsc_Code").change(function () {      
		var inputvalues = $(this).val();      
		  var reg = /[A-Z|a-z]{4}[0][a-zA-Z0-9]{6}$/;    
		                if (inputvalues.match(reg)) {    
		                    return true;    
		                }    
		                else {    
		                     $("#id_ifsc_Code").val("");    
		                    alert("You entered invalid IFSC code");    
		                    //document.getElementById("txtifsc").focus();    
		                    return false;    
		                }    
		});   

      $(document).on('change',"#id_mobile", function(){
        var inputvalues = $(this).val();
        var gstinformat = new RegExp("^[6-9][0-9]{9}$");

        if (gstinformat.test(inputvalues)) {
         return true;
        } else {
            alert('Please Enter Valid Mobile Number');
            $("#id_mobile").val('');
            $("#id_mobile").focus();
        }

    });
      $(document).on('change',"#id_alternate_mobile", function(){
        var inputvalues = $(this).val();
        var gstinformat = new RegExp("^[6-9][0-9]{9}$");

        if (gstinformat.test(inputvalues)) {
         return true;
        } else {
            alert('Please Enter Valid Mobile Number');
            $("#id_alternate_mobile").val('');
            $("#id_alternate_mobile").focus();
        }

    });
    </script>
{% endblock saler_body %}

saler/templates/saler/admin2.html
{% extends 'admin/base.html' %}

{% block title %}All Orders{% endblock %}

{% block branding %}
    <h1 style="display: inline;" class="ml-2">All Orders</h1>
{% endblock %}

{% block usertools %}
  {{block.super}}
  <div id="user-tools">
    {% block welcome-msg %}
      {{block.super}}
    {% endblock %}
    {% block userlinks  %}
      {{block.super}}
    {% endblock %}
  </div>
{% endblock %}

  
{% block pretitle %}<h3>All Orderd Products</h3>{% endblock %}

{% block content %}
    <div class="container-fluid">
      <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">order_id</th>
          <th scope="col">mobile</th>
          <th scope="col">alternate mobile</th>
          <th scope="col">Address</th>
        </tr>
      </thead>
      <tbody>
        {% for i in orders %}
        <tr>
          <th scope="row">{{i.order_id}}</th>
          <td>{{i.user.userdetail.mobile}}</td>
          <td>{{i.user.userdetail.alternate_mobile}}</td>
          <td>{{i.user.userdetail.address}}, {{i.user.userdetail.landmark}}, {{i.user.userdetail.locality}}, {{i.user.userdetail.city}}, {{i.user.userdetail.state}}, {{i.user.userdetail.pincode}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    </div>
  {{ block.super }}
{% endblock %}